const es = {
  signin: '[data-cy="signin"]',
  dialogStudent: '[data-cy="dialog-student"]',
  emailPlaceholder: '[placeholder="Email"]',
  passwordPlaceholder: '[placeholder="Password"]',
  signinSubmit: '[data-cy="signinsubmit"]',
  exploreCoursesText: '[data-cy="exploreCoursesText"]',
  search: '[data-cy="search"]',
  checkFirstCourse: '[data-cy="checkc"]',
  success: '[data-cy="success"]',
  sampleCourseHeaderText: '[data-cy="sampleCourseHeaderText"]',
  qa: '[data-cy="qa"]',
  question: '[data-cy="question"]',
  answer: '[data-cy="answer"]',
  submitqa: '[data-cy="submitqa"]',
  reviews: '[data-cy="reviews"]',
  revArea: '[data-cy="revArea"]',
  notes: '[data-cy="notes"]',
  noteT: '[data-cy="noteT"]',
  noteD: '[data-cy="noteD"]',
  noteS: '[data-cy="noteS"]',
  theme: '[data-cy="theme"]',
  lang: '[data-cy="lang"]',
};
export default es;
