const es = {
  addCourse: '[data-cy="add-course"]',
  title: '[data-cy="title"]',
  desc: '[data-cy="desc"]',
  cat: '[data-cy="cat"]',
  addCat: '[data-cy="addcat"]',
  price: '[data-cy="price"',
  discount: '[data-cy="discount"',
  sub: '[data-cy="sub"',
  addLessons: '[data-cy="addlessons"]',
  add: '[data-cy="add"]',
  submit: '[data-cy="submit"]',
  lecture: '[data-cy="lecture"]',
  inputFile: "input[type=file]",
  section: '[data-cy="section"]',
  vListItem: ".v-list-item",
  exercise: '[data-cy="exercise"]',
  qInput: '[data-cy="qInput"]',
  qOutput: '[data-cy="qOutput"]',
  review: '[data-cy="review"]',
  allCourses: '[data-cy="allcourses"]',
  profile: '[data-cy="profile"]',
  edit: '[data-cy="edit"]',
  smtitle: '[data-cy="smtitle"]',
  smlink: '[data-cy="smlink"]',
  profsub: '[data-cy="profsub"]',
  signin: '[data-cy="signin"]',
  dialogInstructor: '[data-cy="dialog-instructor"]',
  email: '[placeholder="Email"]',
  password: '[placeholder="Password"]',
  signinSubmit: '[data-cy="signinsubmit"]',
};
export default es;
